; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{0D075D57-B6C5-477F-9280-775FEF0D655D}
AppName=gifSlap
AppVersion=0.7.7
;AppVerName=gifSlap 0.0.0
AppPublisher=Gridwalk Labs
AppPublisherURL=http://gifslap.com
AppSupportURL=http://gifslap.com
AppUpdatesURL=http://gifslap.com
DefaultDirName={localappdata}\gifSlap
DisableDirPage=yes
DefaultGroupName=gifSlap
LicenseFile={{gifSlap-repository-path}}dev\win\gifSlap_License_Agreement.txt
OutputDir={{gifSlap-repository-path}}dist
OutputBaseFilename=gifSlap_setup_0.7.7_pc
SetupIconFile={{gifSlap-repository-path}}dev\win\gifslap-icon.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "{{gifSlap-repository-path}}dev\win\gifSlap.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{{gifSlap-repository-path}}dev\win\d3dcompiler_47.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{{gifSlap-repository-path}}dev\win\ffmpegsumo.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{{gifSlap-repository-path}}dev\win\gifSlap_License_Agreement.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "{{gifSlap-repository-path}}dev\win\icudtl.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "{{gifSlap-repository-path}}dev\win\libEGL.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{{gifSlap-repository-path}}dev\win\libGLESv2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{{gifSlap-repository-path}}dev\win\nw.pak"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\gifSlap"; Filename: "{app}\gifSlap.exe"
Name: "{group}\{cm:ProgramOnTheWeb,gifSlap}"; Filename: "http://gifslap.com"
Name: "{group}\{cm:UninstallProgram,gifSlap}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\gifSlap"; Filename: "{app}\gifSlap.exe"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\gifSlap"; Filename: "{app}\gifSlap.exe"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\gifSlap.exe"; Description: "{cm:LaunchProgram,gifSlap}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: filesandordirs; Name: "{localappdata}\gifSlap"